package rs.ac.bg.etf.pp1;

public class sym_old {
	  public static final int LBRACKET = 9;
	  public static final int CONST = 5;
	  public static final int NUMCONST = 34;
	  public static final int NOTEQUAL = 28;
	  public static final int LPAREN = 11;
	  public static final int GREATER = 29;
	  public static final int SEMI = 6;
	  public static final int LESS = 31;
	  public static final int MINUS = 20;
	  public static final int RPAREN = 12;
	  public static final int COMMA = 7;
	  public static final int INC = 18;
	  public static final int EQUALEQUAL = 27;
	  public static final int DIV = 24;
	  public static final int PLUS = 22;
	  public static final int IF = 38;
	  public static final int LESSEQ = 32;
	  public static final int EXP = 26;
	  public static final int DOT = 39;
	  public static final int EOF = 0;
	  public static final int RETURN = 40;
	  public static final int RBRACKET = 10;
	  public static final int EQUAL = 8;
	  public static final int NEW = 21;
	  public static final int error = 1;
	  public static final int MUL = 23;
	  public static final int MOD = 25;
	  public static final int IDENT = 33;
	  public static final int VOID = 13;
	  public static final int COLON = 14;
	  public static final int ELSE = 37;
	  public static final int LBRACE = 3;
	  public static final int READ = 15;
	  public static final int GOTO = 17;
	  public static final int CHARCONST = 35;
	  public static final int RBRACE = 4;
	  public static final int BOOLCONST = 36;
	  public static final int PROG = 2;
	  public static final int GREATEREQ = 30;
	  public static final int DEC = 19;
	  public static final int PRINT = 16;
	}
